### ISSUE TITLE
npm run resolve に失敗する

### ISSUE THREAD

**Issue by SuguruOoki** [connthass/api-docs#17]
# 概要

手順通りに環境構築を進めるとnpm run resolveに失敗する。

## バージョン情報

```
npm: 6.12.0
node: v10.16.0
nodebrew: 1.0.1
```

## 実際のエラー

```
npm run resolve                                                                                   [master] ttys000 [11/17 15:39:23]

> syuukai@1.0.0 resolve /Users/suguruohki/workspace/test-space/personal/api-docs
> multi-file-openapi -e openapi/index.yaml -o openapi.yaml

YAML file resolve completed
/Users/suguruohki/workspace/test-space/personal/api-docs/node_modules/multi-file-openapi/resolve.js:18
            throw err;
            ^

Error: EISDIR: illegal operation on a directory, open 'openapi.yaml'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! syuukai@1.0.0 resolve: `multi-file-openapi -e openapi/index.yaml -o openapi.yaml`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the syuukai@1.0.0 resolve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/suguruohki/.npm/_logs/2019-11-17T06_39_29_365Z-debug.log
```
### ログ情報

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/suguruohki/.nodebrew/node/v10.16.0/bin/node',
1 verbose cli   '/Users/suguruohki/.nodebrew/current/bin/npm',
1 verbose cli   'run',
1 verbose cli   'resolve' ]
2 info using npm@6.12.0
3 info using node@v10.16.0
4 verbose run-script [ 'preresolve', 'resolve', 'postresolve' ]
5 info lifecycle syuukai@1.0.0~preresolve: syuukai@1.0.0
6 info lifecycle syuukai@1.0.0~resolve: syuukai@1.0.0
7 verbose lifecycle syuukai@1.0.0~resolve: unsafe-perm in lifecycle true
8 verbose lifecycle syuukai@1.0.0~resolve: PATH: /Users/suguruohki/.nodebrew/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/suguruohki/workspace/test-space/personal/api-docs/node_modules/.bin:/Users/suguruohki/.ebcli-virtual-env/executables:/Users/suguruohki/.ebcli-virtual-env/executables:/Users/suguruohki/.nodebrew/current/bin:/usr/local/opt/php@7.3/bin:/usr/local/var/pyenv/shims:/usr/local/bin:/Users/suguruohki/.ebcli-virtual-env/executables:/Users/suguruohki/.ebcli-virtual-env/executables:/Users/suguruohki/.nodebrew/current/bin:/usr/local/opt/php@7.3/bin:/usr/local/var/pyenv/shims:/usr/local/bin:/Users/suguruohki/.ebcli-virtual-env/executables:/Users/suguruohki/.ebcli-virtual-env/executables:/Users/suguruohki/.nodebrew/current/bin:/usr/local/opt/php@7.3/bin:/usr/local/var/pyenv/shims:/usr/local/bin:/Users/suguruohki/.ebcli-virtual-env/executables:/Users/suguruohki/.nodebrew/current/bin:/usr/local/opt/php@7.3/bin:/usr/local/var/pyenv/shims:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/suguruohki/bin:/usr/local/bin:/bin:/Users/suguruohki/bin:/usr/local/bin:/bin:/Users/suguruohki/bin:/usr/local/bin:/bin:/Users/suguruohki/bin:/usr/local/bin:/bin
9 verbose lifecycle syuukai@1.0.0~resolve: CWD: /Users/suguruohki/workspace/test-space/personal/api-docs
10 silly lifecycle syuukai@1.0.0~resolve: Args: [ '-c',
10 silly lifecycle   'multi-file-openapi -e openapi/index.yaml -o openapi.yaml' ]
11 silly lifecycle syuukai@1.0.0~resolve: Returned: code: 1  signal: null
12 info lifecycle syuukai@1.0.0~resolve: Failed to exec resolve script
13 verbose stack Error: syuukai@1.0.0 resolve: `multi-file-openapi -e openapi/index.yaml -o openapi.yaml`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/suguruohki/.nodebrew/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/suguruohki/.nodebrew/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid syuukai@1.0.0
15 verbose cwd /Users/suguruohki/workspace/test-space/personal/api-docs
16 verbose Darwin 18.7.0
17 verbose argv "/Users/suguruohki/.nodebrew/node/v10.16.0/bin/node" "/Users/suguruohki/.nodebrew/current/bin/npm" "run" "resolve"
18 verbose node v10.16.0
19 verbose npm  v6.12.0
20 error code ELIFECYCLE
21 error errno 1
22 error syuukai@1.0.0 resolve: `multi-file-openapi -e openapi/index.yaml -o openapi.yaml`
22 error Exit status 1
23 error Failed at the syuukai@1.0.0 resolve script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by SuguruOoki** [comment]
![スクリーンショット 2019-11-17 15 48 57](https://user-images.githubusercontent.com/16362021/69004165-0390a200-0952-11ea-8644-380e883f9e64.png)

ディレクトリとしてopenapi.yamlが作成されていたため、ファイルの読み込みがうまくいっていなかったことがswagger-uiの画面がひらけなかった原因の模様。
削除したところうまくいった。
なぜこのディレクトリが作成されるのかについては、不明。
